package com.example.demo.dao.mapper;

import com.example.demo.dao.MqttMessageExample;
import com.example.demo.entity.archive.MqttMessage;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MqttMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mqtt_message
     *
     * @mbg.generated Wed Apr 29 16:40:40 CST 2026
     */
    long countByExample(MqttMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mqtt_message
     *
     * @mbg.generated Wed Apr 29 16:40:40 CST 2026
     */
    int deleteByExample(MqttMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mqtt_message
     *
     * @mbg.generated Wed Apr 29 16:40:40 CST 2026
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mqtt_message
     *
     * @mbg.generated Wed Apr 29 16:40:40 CST 2026
     */
    int insert(MqttMessage row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mqtt_message
     *
     * @mbg.generated Wed Apr 29 16:40:40 CST 2026
     */
    int insertSelective(MqttMessage row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mqtt_message
     *
     * @mbg.generated Wed Apr 29 16:40:40 CST 2026
     */
    List<MqttMessage> selectByExample(MqttMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mqtt_message
     *
     * @mbg.generated Wed Apr 29 16:40:40 CST 2026
     */
    MqttMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mqtt_message
     *
     * @mbg.generated Wed Apr 29 16:40:40 CST 2026
     */
    int updateByExampleSelective(@Param("row") MqttMessage row, @Param("example") MqttMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mqtt_message
     *
     * @mbg.generated Wed Apr 29 16:40:40 CST 2026
     */
    int updateByExample(@Param("row") MqttMessage row, @Param("example") MqttMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mqtt_message
     *
     * @mbg.generated Wed Apr 29 16:40:40 CST 2026
     */
    int updateByPrimaryKeySelective(MqttMessage row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mqtt_message
     *
     * @mbg.generated Wed Apr 29 16:40:40 CST 2026
     */
    int updateByPrimaryKey(MqttMessage row);
}