package com.example.demo.entity.archive;

import java.util.Date;

public class MqttMessage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mqtt_message.id
     *
     * @mbg.generated Wed Apr 29 16:40:40 CST 2026
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mqtt_message.message
     *
     * @mbg.generated Wed Apr 29 16:40:40 CST 2026
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mqtt_message.save_time
     *
     * @mbg.generated Wed Apr 29 16:40:40 CST 2026
     */
    private Date saveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mqtt_message.isdeleted
     *
     * @mbg.generated Wed Apr 29 16:40:40 CST 2026
     */
    private Boolean isdeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mqtt_message.id
     *
     * @return the value of mqtt_message.id
     *
     * @mbg.generated Wed Apr 29 16:40:40 CST 2026
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mqtt_message.id
     *
     * @param id the value for mqtt_message.id
     *
     * @mbg.generated Wed Apr 29 16:40:40 CST 2026
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mqtt_message.message
     *
     * @return the value of mqtt_message.message
     *
     * @mbg.generated Wed Apr 29 16:40:40 CST 2026
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mqtt_message.message
     *
     * @param message the value for mqtt_message.message
     *
     * @mbg.generated Wed Apr 29 16:40:40 CST 2026
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mqtt_message.save_time
     *
     * @return the value of mqtt_message.save_time
     *
     * @mbg.generated Wed Apr 29 16:40:40 CST 2026
     */
    public Date getSaveTime() {
        return saveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mqtt_message.save_time
     *
     * @param saveTime the value for mqtt_message.save_time
     *
     * @mbg.generated Wed Apr 29 16:40:40 CST 2026
     */
    public void setSaveTime(Date saveTime) {
        this.saveTime = saveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mqtt_message.isdeleted
     *
     * @return the value of mqtt_message.isdeleted
     *
     * @mbg.generated Wed Apr 29 16:40:40 CST 2026
     */
    public Boolean getIsdeleted() {
        return isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mqtt_message.isdeleted
     *
     * @param isdeleted the value for mqtt_message.isdeleted
     *
     * @mbg.generated Wed Apr 29 16:40:40 CST 2026
     */
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }
}